### PR TITLE
Start of the advection example (MPI not working)

### PR DESCRIPTION
**Pull request by jkozdon**
I have started the advection example, BUT there is a problem with the mpi when there are more than two ranks.

Probably best not to actually merge into master but wanted to get feedback/review to see if @lcw or @fxgiraldo can see the problem.

### CODE REVIEW

**Comment by lcw** [comment]
I see a problem with three ranks as well.  If I turn off mesh warping then it seems to go away.  Let me know if you find the issue or get a smaller test case.  I can look at this more Friday.

**Comment by lcw** [comment]
I am guessing it is an issue with the element connectivity information.

**Comment by jkozdon** [comment]
Thanks. Will take a look at the warpings. Maybe I don't handle the ghost right.

On Sep 27, 2018, at 8:29 AM, Lucas C Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


I see a problem with three ranks as well. If I turn off mesh warping then it seems to go away. Let me know if you find the issue or get a smaller test case. I can look at this more Friday.

**Comment by lcw** [comment]
A 4x4 mesh seems to have the same problem.  I will check the connectivity by hand.  We should be able to copy and modify [mpi_test_connect.jl](https://github.com/climate-machine/Canary.jl/blob/master/test/mpi_test_connect.jl) which checks a similar mesh.

**Comment by jkozdon** [comment]
3 x 2 with two ranks has problems as well.

Seems to be that when one cell is needed twice by a neighbor maybe there is a problem.

Not sure it's the connectivity since the `vmapP` and `vmapM` check out in parallel (at least with non-periodic BC)

On Sep 27, 2018, at 9:53 AM, Lucas C Wilcox <notifications@github.com<mailto:notifications@github.com>> wrote:


A 4x4 mesh seems to have the same problem. I will check the connectivity by hand. We should be able to copy and modify mpi_test_connect.jl<https://github.com/climate-machine/Canary.jl/blob/master/test/mpi_test_connect.jl> which checks a similar mesh.

**Comment by jkozdon** [comment]
I went ahead and merged this so that @fxgiraldo can start working on the 1-d and Euler codes.

**Pull request merged**
