### PR TITLE
Fixing codecov to prevent pull request comments

### PR DESCRIPTION
**Pull request by jkozdon**

### CODE REVIEW

**Comment by jkozdon** [comment]
I'm trying to prevent codecov from commenting on pull requests...

**Comment by jkozdon** [comment]
It seems that the code coverage YML file isn't properly read when named `.codecov.yml` but is when it is called `codecov.yml`.

Thoughts? Docs seem to suggest both are valid names...

**Comment by lcw** [comment]
I am ambivalent about the comments.  So unless there is a push to remove them I will just leave it as it is.

**Comment by lcw** [comment]
Let's just leave it how it is for now.  We can reopen this if we change our mind in the future.

**Pull request closed without merging**
